eureka:
  client:
    service-url: # EurekaServer的地址，现在是自己的地址，如果是集群，需要加上其它Server的地址。
      defaultZone: http://172.16.185.134:8088/eureka/

spring:
  application:
      name: crm-sales-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://115.159.74.109:3306/crm?useUnicode=true&characterEncoding=utf-8
    username: root
    password: xj461352520


server:
  port: 8080
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/css
      - application/x-font-ttf
      - application/javascript
      - application/json

mybatis:
  typeAliasesPackage: org.xujin.crm.sales.tunnel.dataobject
  mapper-locations:
  - classpath:mapper/*.xml